name: example
description: Example
repository: https://github.com/kimmy-wang/dio_annotation/tree/main/example
publish_to: none

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  dio: ^5.0.0
  dio_annotation:

dev_dependencies:
  build_runner: ^2.4.10
  dio_runner:
  very_good_analysis: ^5.1.0
