name: example
description: Example
repository: https://github.com/kw214/dio_annotation/tree/main/example
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  dio_annotation:

dev_dependencies:
  build_runner:
  dio_runner:
  very_good_analysis: ^3.1.0
