name: dio_annotation
description: Dio Annotation
repository: https://github.com/kw214/dio_annotation/tree/main/dio_annotation
version: 0.0.1-alpha.2

environment:
  sdk: ">=2.18.0 <3.0.0"

dev_dependencies:
  very_good_analysis: ^3.1.0
