name: dio_annotation
description: Dio Annotation
repository: https://github.com/kimmy-wang/dio_annotation/tree/main/dio_annotation
topics:
  - dio
  - annotation
  - dio-annotation
version: 0.0.2

environment:
  sdk: '>=3.4.0 <4.0.0'

dev_dependencies:
  very_good_analysis: ^5.1.0
