name: dio_annotation
description: Dio Annotation
repository: https://github.com/kw214/dio_annotation/tree/main/dio_annotation
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  very_good_analysis: ^5.1.0
